###############################################################################
# THE HOME ASSISTANT CONFIGURATION FILE - MOTHER OF ALL CONFIG FILES
# @Author   :   Mahasri Kalavala
# @Date     :   04/15/2017
###############################################################################
homeassistant:
  name: Home 
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret time_zone
  customize_glob: !include customize_glob.yaml  
  packages: !include_dir_named packages

ios:
updater:
discovery:
frontend:
sun:
config:
logbook:
conversation:
history:

http:
  api_password: !secret api_password

mqtt:
  broker: !secret pi_hole_mqtt_server
  port: !secret pi_hole_mqtt_port
  username: !secret pi_hole_mqtt_username
  password: !secret pi_hole_mqtt_password
  keepalive: 60
  client_id: pi_ha

binary_sensor:
  - platform: workday
    country: US

logger: !include logging.yaml
group: !include_dir_merge_named groups


ios:
  push:
    categories:
      - name: Single Car Garage Door
        identifier: '1CAR_GARAGE'
        actions:
          - identifier: '1CAR_GARAGE_CLOSE'
            title: 'Close Garage Door'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
      - name: Two Car Garage Door
        identifier: '2CAR_GARAGE'
        actions:
          - identifier: '2CAR_GARAGE_CLOSE'
            title: 'Close Garage Door'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
      - name: Trash Recycle
        identifier: 'TRASH_RECYCLE'
        actions:
          - identifier: 'TRASH_LEFT'
            title: 'Done'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'TRASH_REMIND_LATER'
            title: 'Remind Later'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  
