###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Batteries
#   @description    :   Status about various baterries (iphones, sensors...etc)
###############################################################################
homeassistant:
  customize:
    sensor.hasikas_iphone_battery:
      hidden: True
    sensor.mallikas_iphone_battery:
      hidden: True
    sensor.srinikas_iphone_battery:
      hidden: True
    sensor.sureshs_iphone_battery:
      hidden: True

    sensor.suresh_iphone_battery:
      friendly_name: Suresh's iPhone Battery
    sensor.mallika_iphone_battery:
      friendly_name: Mallika's iPhone Battery
    sensor.srinika_iphone_battery:
      friendly_name: Srinika's iPhone Battery
    sensor.hasika_iphone_battery:
      friendly_name: Hasika's iPhone Battery

# Multi Sensor Batteries
    sensor.upstairs_multisensor_battery:
      friendly_name: Upstairs Multisensor Battery
    sensor.downstairs_multisensor_battery:
      friendly_name: Downstairs Multisensor Battery
    sensor.single_car_garage_door_sensor_battery:
      friendly_name: Single Car Garage Door Sensor Battery
    sensor.two_car_garage_door_sensor_battery:
      friendly_name: Two Car Garage Door Sensor Battery
    automation.alert_low_battery_level_of_multisensors:
      friendly_name: Alert Low Battery of Multisensors
      icon: mdi:battery

sensor:
  - platform: template
    sensors:
      suresh_iphone_battery:
        unit_of_measurement: '%'
        entity_id: device_tracker.suresh_suresh
        value_template: "{{ (states.device_tracker.suresh_suresh.attributes|default).battery|default|int('unknown') }}"
        icon_template: >-
          {% set battery_level = states('sensor.sureshs_iphone_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
  
  - platform: template
    sensors:
      mallika_iphone_battery:
        unit_of_measurement: '%'
        entity_id: device_tracker.mallika_mallika
        value_template: "{{ (states.device_tracker.mallika_mallika.attributes|default).battery|default|int('unknown') }}"
        icon_template: >-
          {% set battery_level = states('sensor.mallikas_iphone_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
  
  - platform: template
    sensors:
      srinika_iphone_battery:
        unit_of_measurement: '%'
        entity_id: device_tracker.srinika_srinika
        value_template: "{{ (states.device_tracker.srinika_srinika.attributes|default).battery|default|int('unknown') }}"
        icon_template: >-
          {% set battery_level = states('sensor.srinikas_iphone_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
  
  - platform: template
    sensors:
      hasika_iphone_battery:
        unit_of_measurement: '%'
        entity_id: device_tracker.hasika_hasika
        value_template: "{{ (states.device_tracker.hasika_hasika.attributes|default).battery|default|int('unknown') }}"
        icon_template: >-
          {% set battery_level = states('sensor.hasikas_iphone_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: mqtt
    state_topic: "owntracks/mallika/mallika"
    name: "Mallika's iPhone Battery"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt }}"
    
  - platform: mqtt
    state_topic: "owntracks/suresh/suresh"
    name: "Suresh's iPhone Battery"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt }}"
  
  - platform: mqtt
    state_topic: "owntracks/srinika/Srinika"
    name: "Srinika's iPhone Battery"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt }}"
      
  - platform: mqtt
    state_topic: "owntracks/hasika/Hasika"
    name: "Hasika's iPhone Battery"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt }}"

automation:
  - alias: Notify Low battery
    trigger:
      platform: numeric_state
      entity_id:
      - device_tracker.suresh_suresh
      - device_tracker.mallika_mallika
      - device_tracker.srinika_srinika
      - device_tracker.hasika_hasika
      value_template: '{{ state.attributes.battery }}'
      below: 30
    action:
      - service: script.notify_me
        data_template:
          value1: >
            {{ trigger.to_state.attributes.friendly_name }}'s phone battery is less than: {{ trigger.to_state.attributes.battery }}%.
          value2: ""

  - alias: Alert Low Battery Level of Sensors
    trigger:
      platform: numeric_state
      entity_id:
      - sensor.upstairs_multisensor_battery
      - sensor.downstairs_multisensor_battery
      - sensor.single_car_garage_door_sensor_battery
      - sensor.two_car_garage_door_sensor_battery
      below: 20
    action:
      - service: script.notify_me
        data_template:
          value1: >
            Action Required: {{ trigger.to_state.attributes.friendly_name }}'s battery is: {{ trigger.to_state.state }}%.
          value2: ""
