###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Home Assistant
#   @description    :   Bunch of Sensors that are system or environment related
###############################################################################
homeassistant:
  customize:
  
    sensor.external_ip:
      friendly_name: External IP Address

# Speed Test Sensor
    sensor.speedtest_ping:
      friendly_name: Ping Speed

    sensor.speedtest_upload:
      friendly_name: Upload Speed

    sensor.speedtest_download:
      friendly_name: Download Speed

    sensor.dns_queries_today:
      friendly_name: DNS Queries today 
     
# Pi-Hole Sensor
    sensor.ads_percentage_today:
      friendly_name: Percentage of Ad Traffic Blocked
      unit_of_measurement: '%'
     
    sensor.domains_being_blocked:
      friendly_name: Total Domains Blocking

    sensor.ads_blocked_today:
      friendly_name: Ads Blocked Today
      icon: mdi:do-not-disturb

# System Info Sensor
    sensor.cpu_speed:
      friendly_name: CPU Speed

    sensor.cpu_use:
      friendly_name: CPU Usage

    sensor.disk_free_:
      friendly_name: Available Disk

    sensor.ram_free:
      friendly_name: Available Memory

    sensor.ipv4_address_wlan0:
      friendly_name: IP Address

    sensor.last_boot:
      friendly_name: Last Boot

    sensor.since_last_boot:
      friendly_name: Up Since

    sensor.time:
      friendly_name: Time

    sensor.date:
      friendly_name: Date

    automation.login_failure:
      friendly_name: Alert Login Failures

    automation.startup_notification:
      friendly_name: Notify Startup Events
      icon: mdi:thumb-up

    automation.update_available_notification:
      friendly_name: Notify of new updates
      icon: mdi:update    

sensor:
  - platform: rest
    resource: http://ip.jsontest.com
    name: external_ip
    value_template: '{{ value_json.ip }}'

  - platform: command_line
    name: CPU Temperature
    command: cat /sys/class/thermal/thermal_zone0/temp
    unit_of_measurement: 'F'
    value_template: '{{ (value|int / 1000 * 1.8 + 32)|round(1) }}'

  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  - platform: speedtest
    minute: 30
    hour:
      - 0
      - 6
      - 12
      - 18
    monitored_conditions:
      - ping
      - download
      - upload
  
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: ipv4_address
        arg: wlan0
      - type: last_boot
      - type: since_last_boot
    
  - platform: rest
    name: dns_queries_today
    resource: http://192.168.200.50/admin/api.php  
    value_template: '{{ value_json.dns_queries_today }}'
  
  - platform: rest
    name: domains_being_blocked
    resource: http://192.168.200.50/admin/api.php  
    value_template: '{{ value_json.domains_being_blocked }}'
  
  - platform: rest
    name: ads_blocked_today
    resource: http://192.168.200.50/admin/api.php  
    value_template: '{{ value_json.ads_blocked_today }}'
  
  - platform: rest
    name: ads_percentage_today
    resource: http://192.168.200.50/admin/api.php  
    value_template: '{{ value_json.ads_percentage_today }}'
  
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    name: HA Current Version
    
  - platform: command_line
    name: HA Installed Version
    command: /srv/homeassistant/homeassistant_venv/bin/hass --version
  
  - platform: template
    sensors:
      ha_last_restart:
        value_template: '{{ as_timestamp(states.automation.startup_notification.attributes.last_triggered) | timestamp_custom("%b %d %X") }}'
        friendly_name: HA Last Restart

automation:

  - alias: Notify Of New External IP
    trigger:
      platform: state
      entity_id: sensor.external_ip
    condition:
      - condition: template
        value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
      - service: script.notify_me
        data_template:
          value1: "Your External IP changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"
          value2: ""

  - alias: Update Available Notification
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      - service: script.notify_me
        data: {"value1":"New HASS update is available. Please update!", "value2":""}
        
  - alias: Clear TTS Cache
    trigger:
      platform: time
      after: '4:45:00'
    action:
      service: tts.clear_cache

  - alias: Startup Notification
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: script.pushbullet_notify
        data: { "value1":"Home Assistant restarted successfully!", "value2":""}      
