homeassistant:
  customize:
    group.ios:
      order: 98

    device_tracker.ipad:
      hidden: true
    device_tracker.suresh:
      hidden: true
    device_tracker.mallika:
      hidden: true
    device_tracker.srinika:
      hidden: true
    device_tracker.hasika:
      hidden: true
    
    sensor.hasikas_iphone_battery:
      hidden: true
    sensor.mallikas_iphone_battery:
      hidden: true
    sensor.srinikas_iphone_battery:
      hidden: true
    sensor.sureshs_iphone_battery:
      hidden: true

    sensor.sureshs_iphone_battery_ot:
      friendly_name: Suresh's iPhone Battery (OT)
      hidden: true
    sensor.mallikas_iphone_battery_ot:
      friendly_name: Mallika's iPhone Battery (OT)
      hidden: true
    sensor.srinikas_iphone_battery_ot:
      friendly_name: Srinika's iPhone Battery (OT)
      hidden: true
    sensor.hasikas_iphone_battery_ot:
      friendly_name: Hasika's iPhone Battery (OT)
      hidden: true
      
# Battery States
    sensor.suresh_iphone_battery:
      friendly_name: Suresh's iPhone Battery
      hidden: true
    sensor.mallika_iphone_battery:
      friendly_name: Mallika's iPhone Battery
      hidden: true
    sensor.srinika_iphone_battery:
      friendly_name: Srinika's iPhone Battery
      hidden: true
    sensor.hasika_iphone_battery:
      friendly_name: Hasika's iPhone Battery  
      hidden: true

# Battery Levels
    sensor.iphone_battery_level:
      friendly_name: Suresh's iPhone Battery Level
      hidden: true
    sensor.iphone__battery_level:
      friendly_name: Mallika's iPhone Battery Level 
      hidden: true
    sensor.suresh_battery_level:
      friendly_name: Suresh's Battery Level
      hidden: true
    sensor.mallika_battery_level:
      friendly_name: Mallika's Battery Level
      hidden: true
    sensor.srinika_battery_level:
      friendly_name: Srinika's Battery Level
      hidden: true
    sensor.hasika_battery_level:
      friendly_name: Hasika's Battery Level
      hidden: true

    sensor.iphone_battery_state:
      friendly_name: Suresh's iPhone Battery State
      hidden: true
    sensor.iphone__battery_state:
      friendly_name: Mallika's iPhone Battery State
      hidden: true
    sensor.suresh_battery_state:
      friendly_name: Suresh's Battery State
      hidden: true
    sensor.mallika_battery_state:
      friendly_name: Mallika's Battery State
      hidden: true
    sensor.srinika_battery_state:
      friendly_name: Srinika's Battery State
      hidden: true
    sensor.hasika_battery_state:
      friendly_name: Hasika's Battery State
      hidden: true

    sensor.ipad_battery_level:
      friendly_name: iPad's Battery State
      hidden: true
    sensor.ipad_battery_state:
      friendly_name: iPad's Battery State
      hidden: true

group:
  iOS:
    entities:
      - sensor.suresh_battery_state
      - sensor.suresh_battery_level
      - sensor.mallika__battery_state
      - sensor.mallika__battery_level
      - sensor.srinika_battery_state
      - sensor.srinika_battery_level
      - sensor.hasika_battery_state
      - sensor.hasika_battery_level
      - sensor.ipad_battery_state
      - sensor.ipad_battery_level
      - sensor.iphone_battery_level
      - sensor.iphone_battery_state
      - sensor.iphone__battery_state
      - sensor.iphone__battery_level
