homeassistant:
  customize:
    binary_sensor.ring_front_door_ding:
      friendly_name: Door Sensor Ding
    binary_sensor.ring_front_door_motion:
      friendly_name: Front Door Motion
    sensor.ring_front_door_battery:
      friendly_name: Ring Battery
      hidden: true
    sensor.ring_front_door_last_activity:
      friendly_name: Ring Last Activity
    sensor.ring_front_door_last_ding:
      friendly_name: Ring Last Ding
    sensor.ring_front_door_last_motion:
      friendly_name: Last Ring Motion    
    sensor.ring_front_door_volume:
      friendly_name: Ring Front Door Volume

group:
  Ring Door Bell:
    entities:
      - binary_sensor.ring_front_door_ding
      - binary_sensor.ring_front_door_motion
      - sensor.ring_front_door_battery
      - sensor.ring_front_door_last_activity
      - sensor.ring_front_door_last_ding
      - sensor.ring_front_door_last_motion
      - sensor.ring_front_door_volume
      - automation.motion_detected_at_the_front_door

ring:
  username: !secret ring_username
  password: !secret ring_password
      
sensor:
  - platform: ring
    monitored_conditions:
      - battery
      - last_activity
      - last_ding
      - last_motion
      - volume

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

automation:

  - alias: Motion Detected at the Front Door
    initial_state: true
    hide_entity: false
    trigger:
      platform: state
      entity_id: binary_sensor.ring_front_door_motion
      to: 'on'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
    action:
      - service: mqtt.publish
        data:
          topic: /home/tv/backlight
          payload: 'FLICKER'
          retain: true
      - service: light.lifx_effect_breathe
        data:
          entity_id: light.dinette
          color_name: red
          cycles: 3
          power_on: true
