###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   WatchDog
#   @description    :   Watchdog Automations
###############################################################################

homeassistant:
  customize:
    input_boolean.working_in_garage:
      friendly_name: Working in Garage
      icon: mdi:worker
    automation.garage_lights_watchdog:
      friendly_name: Garage Lights Watchdog
      icon: mdi:timer
    automation.guest_bedroom_1_light_watchdog:
      friendly_name: Guest Bedroom 1 Light Watchdog
      icon: mdi:timer
    automation.guest_bedroom_2_light_watchdog:
      friendly_name: Guest Bedroom 2 Light Watchdog
      icon: mdi:timer
    automation.kids_bedroom_light_watchdog:
      friendly_name: Kids Bedroom Light Watchdog
      icon: mdi:timer
    automation.prayer_room_light_watchdog:
      friendly_name: Prayer Room Light Watchdog
      icon: mdi:timer

input_boolean:
  working_in_garage:
    name: Working in Garage
    initial: off

automation:
  - alias: Working In Garage WatchDog
    trigger:
      - platform: state
        entity_id:
          - input_boolean.working_in_garage
        state: 'on'
        for: 
          hours: 2
    action:
      - service: script.notify_me
        data: { "value1":"It has been two hours, are you still working in the garage?", "value2":" Changing the status to 'Not working'!"}
      - service: input_boolean.turn_off
        entity_id: input_boolean.working_in_garage
  
  - alias: Single Car garage Door WatchDog
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.ecolink_garage_door_tilt_sensor_sensor_5_0
        state: 'on'
        for: 
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.working_in_garage
        state: 'off'
    action:
      - service: script.notify_me
        data: {"value1":"Single Car Garage Door is OPEN for more than 5 minutes!", "value2":""}
      - service: script.voice_notify
        data_template:
          value1: "Attention! Your single car garage door is open for more than 5 minutes."
          value2: ""
  
  - alias: Two Car garage Door WatchDog
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.ecolink_garage_door_tilt_sensor_sensor_4_0
        state: 'on'
        for: 
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.working_in_garage
        state: 'off'
    action:
      - service: script.notify_me
        data: {"value1":"Your Two Car Garage Door is OPEN for more than 5 minutes!", "value2":""}
      - service: script.voice_notify
        data_template:
          value1: "Attention! Your two car garage door is open for more than 5 minutes."
          value2: ""
          
  - alias: Home Security System WatchDog 10 minutes
    trigger:
      - platform: state
        entity_id:
          - alarm_control_panel.simplisafe
        state: 'disarmed'
        for: 
          minutes: 10
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
    action:
      - service: script.notify_me
        data: {"value1":"Home Security System is OFF for more than 10 minutes!", "value2":""}
      - service: script.voice_notify
        data_template:
          value1: "Attention! The Home Security System is OFF for more than 10 minutes!"
          value2: ""
          
  - alias: Home Security System WatchDog 30 minutes
    trigger:
      - platform: state
        entity_id:
          - alarm_control_panel.simplisafe
        state: 'disarmed'
        for: 
          minutes: 30
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
    action:
      - service: script.notify_me
        data: {"value1":"Home Security System is OFF for more than 30 minutes!", "value2":""}
      - service: script.voice_notify
        data_template:
          value1: "Attention! The Home Security System is OFF for more than 10 minutes! This is the last reminder!"
          value2: ""
  
  - alias: Frontroom Light WatchDog
    trigger:
      - platform: state
        entity_id:
          - switch.wemoswitch1
        state: 'on'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      - service: script.notify_me
        data_template:
          value1: >
            {{ trigger.to_state.attributes.friendly_name }} is ON. Saving power by turning it off!
          value2: ""
  
  - alias: Frontyard Light WatchDog
    trigger:
      - platform: state
        entity_id:
          - switch.wemofrontporchlightswitch
        state: 'on'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      - service: script.notify_me
        data_template:
          value1: >
            {{ trigger.to_state.attributes.friendly_name }} is ON during the day time. Saving power by turning it off!
          value2: ""
  
  - alias: Backyard Light WatchDog
    trigger:
      - platform: state
        entity_id:
          - switch.wemobackyardlightswitch
        state: 'on'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      - service: script.notify_me
        data_template:
          value1: >
            {{ trigger.to_state.attributes.friendly_name }} is ON during the day time. Saving power by turning it off!
          value2: ""
  
  - alias: Garage Lights WatchDog
    trigger:
      - platform: state
        entity_id:
          - switch.garage_lights
        state: 'on'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.working_in_garage
        state: 'off'
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      - service: script.notify_me
        data_template:
          value1: >
            {{ trigger.to_state.attributes.friendly_name }} are left ON for about 5 minutes. Saving power by turning it off!
  
  - alias: Guest Bedroom 1 Light WatchDog
    trigger:
      - platform: state
        entity_id:
          - switch.guest_bedroom_1
        state: 'on'
        for:
          minutes: 5
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      - service: script.notify_me
        data_template:
          value1: >
            {{ trigger.to_state.attributes.friendly_name }} lights are left ON for 5 minutes. Saving power by turning it off!
          value2: ""
  
  - alias: Guest Bedroom 2 Light WatchDog
    trigger:
      - platform: state
        entity_id:
          - switch.guest_bedroom_2
        state: 'on'
        for:
          minutes: 10
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      - service: script.notify_me
        data_template:
          value1: >
            {{ trigger.to_state.attributes.friendly_name }} lights are left ON for 10 minutes. Saving power by turning it off!
          value2: ""
  
  - alias: Kids Bedroom Light WatchDog
    trigger:
      - platform: state
        entity_id:
          - switch.kids_bedroom
        state: 'on'
        for:
          minutes: 10
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      - service: script.notify_me
        data_template:
          value1: >
            {{ trigger.to_state.attributes.friendly_name }} lights are left ON for 10 minutes. Saving power by turning it off!
          value2: ""
